version: '3.1'
services:
  wordpress:
    image: bywang/wordpress-env:latest
    restart: always
    links:
      - redis
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      - ./apache2/sites-enabled:/etc/apache2/sites-enabled
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_NAME:
      WORDPRESS_DB_PASSWORD:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
  redis:
    image: redis:alpine
